db:
  driver: postgres
  source: postgresql://root:password@localhost:5432/bank?sslmode=disable
server.address: 0.0.0.0:8080
token:
  symmetric_key: 12345678901234567890123456789012
  access_duration: 15m