env: dev
db:
  driver: postgres
  source: postgresql://root:password@localhost:5432/bank?sslmode=disable
  migration_url: file://db/migration
server:
  http_address: 0.0.0.0:8080
  grpc_address: 0.0.0.0:9090
  redis_address: 0.0.0.0:6379
token:
  symmetric_key: 12345678901234567890123456789012
  access_duration: 15m
  refresh_duration: 24h
email:
  sender:
    name: Simple Bank
    address: simplebank980@gmail.com
    password: zliwbrvrwzrbkkgn
